=== gimballock/raml-workshop/Exercise_2/RestifyEventService/assets/json/event_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type" : "object",
  "properties" : {
    "id" : { "type" : "number" },
    "name" : { "type" : "string", "minLength":1 },
    "description" : { "type" : "string" },
    "location" : { "type" : "string" },
    "starts_at" : { "type" : "string" },
    "ends_at" : { "type" : "string" }
  }
}

=== gimballock/raml-workshop/Exercise_2/OspreyEventService/src/assets/json/events.json
[ 
    { 
      "id":0,
      "name":"APICon SF", 
      "description":"APIcon is a 3-day interactive conference for app developers, existing public API providers, and those currently developing an API strategy.\nFrom May 27-29, 450+ stakeholders in the API economy will gather at the Hilton San Francisco Union Square to learn, create, ideate, and debate while advancing the overall interests of the API economy and all of its constituents. - See more at: http://www.apiconsf.com/#sthash.prwopBLX.dpuf", 
      "location":"750 Kearny St, San Francisco, CA 94108", 
      "starts_at":"2014-05-27",
      "ends_at":"2014-05-29"
    },
    { 
      "id":1,
      "name":"BigDataCamp LA 2014", 
      "description":"BigDataCamp is an unconference where early adopters of BigData technologies, such as Hadoop, exchange ideas. With the rapid change occurring in the industry, we need a place where we can meet to share our experiences, challenges and solutions. At BigDataCamp, you are encouraged to share your thoughts in several open discussions, as we strive for the advancement of BigData. Data Scientists, Developers, IT professionals, users and vendors are all encouraged to participate.", 
      "location":"2230 E Imperial Hwy, El Segundo, CA 90245", 
      "starts_at":"Jun 14, 2014 8:30 am",
      "ends_at":"Jun 14, 2014 7:00 pm"
    },
    { 
      "id":2,
      "name":"DataScienceCamp Silicon Valley", 
      "description":"DataMiningCamp is coming back to Silicon Valley. This year we're calling it DataScienceCamp.", 
      "location":"eBay Town Hall, 2161 North 1st Street, San Jose, CA 95131", 
      "starts_at":"Oct 25, 2014 8:30 am",
      "ends_at":"Oct 25, 2014 9:00 pm"
    },
    { 
      "id":3,
      "name":"CloudCamp London - Internet of Things Special!", 
      "description":"As usual CloudCamp London will be an opportunity to meet old and new friends, grab a beer or two ready for a few short interesting talks and then the lively unpanel debates, follwed by networking accompanied by pizza and more beer!Again the evenings proceeding will be MC'd by @swardley and @cpswan.", 
      "location":"Shoreditch Works, London UK, Shoreditch Works Village Hall, 33 Hoxton Square, London N1 6NN, United Kingdom", 
      "starts_at":"May 07, 2014 6:30 pm",
      "ends_at":"May 07, 2014 9:30 pm"
    }
]
